name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk-softfp:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        git clone https://github.com/Rinnegatamante/vitaGL.git
        make -C vitaGL SOFTFP_ABI=1 NO_DEBUG=1 SAMPLER_UNIFORMS=1 -j$(nproc) install
    - name: Compile project
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Get changelog
      id: changelog
      run: echo "::set-output name=changelog::$(git log -10 --pretty=format:\"%s\")"
    - name: Update release body
      id: update_release
      uses: Rinnegatamante/update_release@master
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        release_name: "Nightly ${{ steps.date.outputs.date }}"
        body: "${{ steps.date.outputs.changelog }}"
        tag: Nightly
    - name: Upload release artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        upload_url: ${{ steps.update_release.outputs.upload_url }}
        asset_path: build/YoYoLoader.vpk
        asset_name: YoYoLoader.vpk
        asset_content_type: application/zip